config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  resources :icos
  root to: "icos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ico.rb
class Ico < ApplicationRecord

  validates :ico_ticker, presence: true
  validates :ico_name, presence: true
  validates :ico_rating, presence: true
  validates :ico_main_sale_open, presence: true
  validates :ico_main_sale_close, presence: true

  validates_uniqueness_of :ico_ticker, :case_sensitive => false

  before_save :uppercase_ico_ticker, :uppercase_ico_name, :check_ico_main_sale

  # default_scope -> { order(updated_at: :desc) }
  # default_scope -> { order(ico_main_sale_open: :desc) }
  # default_scope -> { order(ico_rating: :desc) }
  scope :ico_rating, -> {order(ico_rating: :desc)}

  def uppercase_ico_ticker
    ico_ticker.upcase!
  end

  def uppercase_ico_name
    ico_name.upcase!
  end

  def check_ico_main_sale
    if ico_main_sale_open.nil?
      ico_main_sale_open == now
    end
    if ico_main_sale_close.nil?
      ico_main_sale_open == now
    end

  end



  enum idea_evaluation_type: ['Excellent Idea', 'Good Idea', 'Average Idea', 'Poor Idea']


  enum team_evaluation_type: ['Excellent Team', 'Good Team', 'Average Team', 'Poor Team']


  enum advisors_evaluation_type: ['Zero MVP Advisors', 'One MVP Advisor', 'Two MVP Advisors', 'Three+ Advisors' ]


  enum alpha_beta_evaluation_type: ['No Alpha/Beta', 'Has Alpha/Beta']


  enum token_metrics_evaluation_type: ['No Token', 'Has Token']


  enum platform_app_evaluation_type: ['Platform', 'App']


  enum website_evaluation_type: ['Professional Website', 'Amateur Website']


  enum github_evaluation_type: ['Github - No', 'Github - Yes']


  enum social_evaluation_type: ['1000', '2000', '3000', '4000', '5000', '6000', '7000', '8000', '9000', '10,000']


  enum bounty_evaluation_type: ['No Bounty', 'Has Bounty']


  enum celebrity_evaluation_type: ['No Celebrity', 'Has Celebrity']
end

app/controllers/icos_controller.rb
class IcosController < ApplicationController
  before_action :set_ico, only: [:show, :edit, :update, :destroy]



  # GET /icos
  # GET /icos.json
  def index
    #@icos = Ico.all
    #@icos = Ico.page params[:page]
    @icos = Ico.page(params[:page]).per(10)
    #@icos = Ico.ico_rating.page(params[:page]).per(10)
  end

  # GET /icos/1
  # GET /icos/1.json
  def show
  end

  # GET /icos/new
  def new
    @ico = Ico.new
    @idea_evaluation_types = Ico.idea_evaluation_types
    @team_evaluation_types = Ico.team_evaluation_types
    @advisors_evaluation_types = Ico.advisors_evaluation_types
    @alpha_beta_evaluation_types = Ico.alpha_beta_evaluation_types
    @token_metrics_evaluation_types = Ico.token_metrics_evaluation_types
    @platform_app_evaluation_types = Ico.platform_app_evaluation_types
    @website_evaluation_types = Ico.website_evaluation_types
    @github_evaluation_types = Ico.github_evaluation_types
    @social_evaluation_types = Ico.social_evaluation_types
    @bounty_evaluation_types = Ico.bounty_evaluation_types
    @celebrity_evaluation_types = Ico.celebrity_evaluation_types
  end

  # GET /icos/1/edit
  def edit

    @idea_evaluation_types = Ico.idea_evaluation_types
    @team_evaluation_types = Ico.team_evaluation_types
    @advisors_evaluation_types = Ico.advisors_evaluation_types
    @alpha_beta_evaluation_types = Ico.alpha_beta_evaluation_types
    @token_metrics_evaluation_types = Ico.token_metrics_evaluation_types
    @platform_app_evaluation_types = Ico.platform_app_evaluation_types
    @website_evaluation_types = Ico.website_evaluation_types
    @github_evaluation_types = Ico.github_evaluation_types
    @social_evaluation_types = Ico.social_evaluation_types
    @bounty_evaluation_types = Ico.bounty_evaluation_types
    @celebrity_evaluation_types = Ico.celebrity_evaluation_types
  end

  # POST /icos
  # POST /icos.json
  def create
    @ico = Ico.new(ico_params)

    @idea_evaluation_types = Ico.idea_evaluation_types
    @team_evaluation_types = Ico.team_evaluation_types
    @advisors_evaluation_types = Ico.advisors_evaluation_types
    @alpha_beta_evaluation_types = Ico.alpha_beta_evaluation_types
    @token_metrics_evaluation_types = Ico.token_metrics_evaluation_types
    @platform_app_evaluation_types = Ico.platform_app_evaluation_types
    @website_evaluation_types = Ico.website_evaluation_types
    @github_evaluation_types = Ico.github_evaluation_types
    @social_evaluation_types = Ico.social_evaluation_types
    @bounty_evaluation_types = Ico.bounty_evaluation_types
    @celebrity_evaluation_types = Ico.celebrity_evaluation_types

    respond_to do |format|
      if @ico.save
         #format.html { redirect_to @ico, notice: 'Ico was successfully created.' }
         format.html { redirect_to @ico }
         flash[:success] = "Ico was created successfully!"
        #format.html { redirect_to icos_path(@icos), notice: 'Ico was successfully created.' }
        format.json { render :show, status: :created, location: @ico }
      else
         #byebug
        format.html { render :new }
         format.json { render json: @ico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icos/1
  # PATCH/PUT /icos/1.json
  def update
    respond_to do |format|

      @idea_evaluation_types = Ico.idea_evaluation_types
      @team_evaluation_types = Ico.team_evaluation_types
      @advisors_evaluation_types = Ico.advisors_evaluation_types
      @alpha_beta_evaluation_types = Ico.alpha_beta_evaluation_types
      @token_metrics_evaluation_types = Ico.token_metrics_evaluation_types
      @platform_app_evaluation_types = Ico.platform_app_evaluation_types
      @website_evaluation_types = Ico.website_evaluation_types
      @github_evaluation_types = Ico.github_evaluation_types
      @social_evaluation_types = Ico.social_evaluation_types
      @bounty_evaluation_types = Ico.bounty_evaluation_types
      @celebrity_evaluation_types = Ico.celebrity_evaluation_types

      if @ico.update(ico_params)
        #format.html { redirect_to @ico, notice: 'Ico was successfully updated.' }
        format.html { redirect_to @ico}
        flash[:success] = "Ico was updated successfully!"
        #format.html { redirect_to icos_path(@icos), notice: 'Ico was successfully updated.' }
        format.json { render :show, status: :ok, location: @ico }
      else
        format.html { render :edit }
        format.json { render json: @ico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icos/1
  # DELETE /icos/1.json
  def destroy
    @ico.destroy
    respond_to do |format|
      #format.html { redirect_to icos_url, notice: 'Ico was successfully destroyed.' }
      format.html { redirect_to icos_url }
      flash[:success] = "Ico was successfully deleted!"
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ico
      @ico = Ico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ico_params
      params.require(:ico).permit(:ico_ticker, :ico_name, :ico_rating, :idea_evalution_type, :team_evaluation_type, :advisors_evaluation_type, :alpha_beta_evaluation_type, :token_metrics_evaluation_type, :platform_app_evaluation_type, :website_evaluation_type, :github_evaluation_type, :social_evaluation_type, :bounty_evaluation_type, :celebrity_evaluation_type, :ico_main_sale_open, :ico_main_sale_close)

      # params.fetch(:ico {})
    end
end

app/helpers/icos_helper.rb
module IcosHelper
end

app/views/icos/_form.html.erb
<%= form_with(model: ico, local: true) do |form| %>


    <% if ico.errors.any? %>
        <div class="row">

          <div class="col-xs-12">


            <div class="panel panel-danger">
              <div class="panel-heading">
                <h2 class="panel-title">
                  <%= pluralize(ico.errors.count, "error") %> prohibited this ico from being saved:
                </h2>

                <div class="panel-body">
                  <ul>
                    <% ico.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>


          </div>
        </div>
    <% end %>
    <!--beginning of new row-->
    <div class="row">
      <div class="col-xs-12 form-group">

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Toolbar</h3>
        </div>
        <div class="panel-body">
          <div class="actions center">
            <%= form.submit class: "btn btn-success" %> |
            <%= link_to 'Back', icos_path,  class: "btn btn-warning" %>
          </div>
        </div>
      </div>
    </div>

    </div>

    <!--beginning of new row-->
    <div class="row">

      <div class="col-xs-4 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Ico Ticker</h3>
          </div>
          <div class="panel-body">
            <%= form.text_field :ico_ticker, class: "form-control" %>
          </div>
        </div>

      </div>

      <div class="col-xs-4 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Ico Name</h3>
          </div>
          <div class="panel-body">
            <%= form.text_field :ico_name, class: "form-control" %>
          </div>
        </div>

      </div>

      <div class="col-xs-4 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Ico Rating</h3>
          </div>
          <div class="panel-body">
            <%= form.number_field :ico_rating, class: "form-control" %>
          </div>
        </div>
      </div>

    </div>



    <!--Begining of New Row-->
    <div class="row">
      <div class="col-xs-4 form-group">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Idea Evaluation</h3>
          </div>
          <div class="panel-body">
            <%= form.select :idea_evaluation_type, options_for_select(@idea_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.idea_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>

      </div>
      <div class="col-xs-4 form-group">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Team Evaluation</h3>
          </div>
          <div class="panel-body">
            <%= form.select :team_evaluation_type, options_for_select(@team_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.team_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>
      </div>
      <div class="col-xs-4 form-group">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Advisors Evaluation</h3>
          </div>
          <div class="panel-body">

            <%= form.select :advisors_evaluation_type, options_for_select(@advisors_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.advisors_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>
      </div>
    </div>
    <!--Beginning of new row-->
    <div class="row">
      <div class="col-xs-4 form-group">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Alpha/Beta Evaluation</h3>
          </div>
          <div class="panel-body">

            <%= form.select :alpha_beta_evaluation_type, options_for_select(@alpha_beta_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.alpha_beta_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>

      </div>
      <div class="col-xs-4 form-group">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Token Metrics</h3>
          </div>
          <div class="panel-body">

            <%= form.select :token_metrics_evaluation_type, options_for_select(@token_metrics_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.token_metrics_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>
      </div>

      <div class="col-xs-4 form-group">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Platform or App Evaluation</h3>
          </div>
          <div class="panel-body">

            <%= form.select :platform_app_evaluation_type, options_for_select(@platform_app_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.platform_app_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>

      </div>

    </div>
    <!--Beginning of new row-->
    <div class="row">
      <div class="col-xs-4 form-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Website Evaluation</h3>
          </div>
          <div class="panel-body">

            <%= form.select :website_evaluation_type, options_for_select(@website_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.website_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>
      </div>

      <div class="col-xs-4 form-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Github Evaluation</h3>
          </div>
          <div class="panel-body">

            <%= form.select :github_evaluation_type, options_for_select(@github_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.github_evaluation_type), {}, class: "form-control" %>

          </div>
        </div>

      </div>

      <div class="col-xs-4 form-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Social Evaluation</h3>
          </div>
          <div class="panel-body">
            <%= form.select :social_evaluation_type, options_for_select(@social_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.social_evaluation_type), {}, class: "form-control" %>


          </div>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-xs-6 form-group">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Bounty Evaluation</h3>
          </div>
          <div class="panel-body">
            <%= form.select :bounty_evaluation_type, options_for_select(@bounty_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.bounty_evaluation_type), {}, class: "form-control" %>


          </div>
        </div>
      </div>
      <div class="col-xs-6 form-group">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Celebrity Evaluation</h3>
          </div>
          <div class="panel-body">
            <%= form.select :celebrity_evaluation_type, options_for_select(@celebrity_evaluation_types.collect {|s| [s[0], s[0]]}, selected: @ico.celebrity_evaluation_type), {}, class: "form-control" %>


          </div>
        </div>
      </div>
    </div>

    <!--Beginning of new row-->
    <div class="row">
      <div class="col-xs-6 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Main Sale Begins</h3>
          </div>
          <div class="panel-body">

            <%= form.date_field(:ico_main_sale_open) %>

          </div>
        </div>
      </div>
      <div class="col-xs-6 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Main Sale Ends</h3>
          </div>
          <div class="panel-body">

            <%= form.date_field(:ico_main_sale_close) %>

          </div>
        </div>
      </div>
    </div>



<% end %>

app/views/icos/edit.html.erb
<h1>Editing Ico</h1>

<%= render 'form', ico: @ico %>

app/views/icos/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>" id="flash">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

<h1>Icos <%=fa_icon "rocket"%></h1>
<!--beginning of new row-->
<div class="row">
  <div class="col-xs-12 form-group">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Toolbar</h3>
      </div>
      <div class="panel-body">
        <div class="actions center">
          <%= link_to 'New Ico', new_ico_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>




  <table class="table table-hover">
  <thead>
    <tr>

      <th>Ico Ticker</th>
      <th>Ico Name</th>
      <th>Ico Rating</th>
      <th>Ico Main Sale Begins</th>
      <th>Ico Main Sale Ends</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>

  <%  @icos.each do |ico| %>

      <tr>

        <td class="vert-aligned"><%= link_to ico.ico_ticker, ico, class: "btn btn-link" %></td>
        <td class="vert-aligned"><%= ico.ico_name %></td>
        <td class="vert-aligned"><%= ico.ico_rating %></td>
        <td class="vert-aligned"><%= ico.ico_main_sale_open.strftime('%v') %></td>
        <td class="vert-aligned"><%= ico.ico_main_sale_close.strftime('%v') %></td>

        <td><%= link_to 'Delete', ico_path(ico),  method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>

  </tbody>
</table>

  <%= paginate @icos %>

app/views/icos/new.html.erb
<h1>New Ico</h1>

<%= render 'form', ico: @ico %>

app/views/icos/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>" id="flash">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

  <h1>Ico</h1>


<div class="row">
  <div class="col-xs-12 form-group">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Toolbar</h3>
    </div>
    <div class="panel-body">
      <div class="actions center">
        <%= link_to 'Edit', edit_ico_path(@ico), class: "btn btn-info" %> |
        <%= link_to 'Back', icos_path, class: "btn btn-warning" %>
      </div>
    </div>
  </div>
  </div>
</div>



  <!--beginning of new row-->
  <div class="row">

    <div class="col-xs-4 form-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Ico Ticker</h3>
        </div>
        <div class="panel-body">
          <%= @ico.ico_ticker %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Ico Name</h3>
        </div>
        <div class="panel-body">
          <%= @ico.ico_name %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Ico Rating</h3>
        </div>
        <div class="panel-body">
          <%= @ico.ico_rating %>
        </div>
      </div>
    </div>

  </div>



  <!--beginning of new row-->
  <div class="row">

    <div class="col-xs-4 form-group">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Idea Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.idea_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Team Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.team_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Advisors Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.advisors_evaluation_type  %>
        </div>
      </div>


    </div>

  </div>



  <!--beginning of new row-->
  <div class="row">

    <div class="col-xs-4 form-group">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Alpha/Beta Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.alpha_beta_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Token Metrics</h3>
        </div>
        <div class="panel-body">
          <%= @ico.token_metrics_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Platform or App</h3>
        </div>
        <div class="panel-body">
          <%= @ico.platform_app_evaluation_type  %>
        </div>
      </div>


    </div>

  </div>

  <!--beginning of new row-->
  <div class="row">

    <div class="col-xs-4 form-group">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Website Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.website_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Github Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.github_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 form-group">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Social Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.social_evaluation_type  %>
        </div>
      </div>


    </div>

  </div>

  <!--beginning of new row-->
  <div class="row">

    <div class="col-xs-6 form-group">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Bounty Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.bounty_evaluation_type  %>
        </div>
      </div>

    </div>

    <div class="col-xs-6 form-group">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Celebrity Evaluation</h3>
        </div>
        <div class="panel-body">
          <%= @ico.celebrity_evaluation_type  %>
        </div>
      </div>

    </div>
  </div>


    <!--beginning of new row-->
    <div class="row">
      <div class="col-xs-6 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Main Sale Begins</h3>
          </div>
          <div class="panel-body">
            <%= @ico.ico_main_sale_open  %>
          </div>
        </div>

      </div>
      <div class="col-xs-6 form-group">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Main Sale Ends</h3>
          </div>
          <div class="panel-body">
            <%= @ico.ico_main_sale_close  %>
          </div>
        </div>

      </div>

    </div>